import { useEffect, useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { LineChart } from '../components/dashboard/LineChart'
import { HBarList } from '../components/dashboard/HBarList'

type Summary = { tiles: { clicks: number; impressions: number; avgPosition: number | null; visits: number; usersTotal: number; favoritesTotal: number }; series: { dates: string[]; clicks: number[]; impressions: number[]; visits: number[]; newUsers: number[] } }
type Ranked = { query?: string; page?: string; clicks: number; impressions: number }[]
const fmt = (value: number | null) => value == null ? '—' : value.toLocaleString('ja-JP')

export function DashboardPage() {
  const { session } = useAuth(); const [days, setDays] = useState<7 | 28 | 90>(28)
  const [summary, setSummary] = useState<Summary | null>(null); const [queries, setQueries] = useState<Ranked>([]); const [pages, setPages] = useState<Ranked>([]); const [coverage, setCoverage] = useState({ pagesWithImpressions: 0, sitemapPageCount: 0 }); const [referers, setReferers] = useState<{ referer: string; visits: number }[]>([]); const [dims, setDims] = useState<Record<string, { value: string; visits: number }[]>>({}); const [error, setError] = useState(false); const [more, setMore] = useState(false)
  useEffect(() => { if (!session) return; let cancelled = false; const get = <T,>(path: string) => fetch(path, { headers: { authorization: `Bearer ${session.access_token}` } }).then(async (r) => { if (!r.ok) throw new Error('request failed'); return r.json() as Promise<T> })
    void Promise.all([get<Summary>(`/api/admin/summary?days=${days}`), get<Ranked>(`/api/admin/queries?days=${days}&limit=50`), get<Ranked>(`/api/admin/pages?days=${days}&limit=50`), get<{ pagesWithImpressions: number; sitemapPageCount: number }>(`/api/admin/coverage?days=${days}`), get<{ referer: string; visits: number }[]>(`/api/admin/referers?days=${days}`), get<Record<string, { value: string; visits: number }[]>>(`/api/admin/dims?days=${days}`)]).then(([s, q, p, c, r, d]) => { if (!cancelled) { setSummary(s); setQueries(q); setPages(p); setCoverage(c); setReferers(r); setDims(d); setError(false) } }).catch(() => { if (!cancelled) setError(true) }); return () => { cancelled = true }
  }, [days, session])
  if (error) return <main id="main-content" className="page"><h1>管理ダッシュボード</h1><p>データを取得できませんでした。</p></main>
  if (!summary) return <main id="main-content" className="page"><h1>管理ダッシュボード</h1><p>読み込み中…</p></main>
  if (summary.series.dates.length === 0) return <main id="main-content" className="page"><h1>管理ダッシュボード</h1><p>収集ジョブの初回実行待ちです。</p></main>
  const tiles = [['クリック', summary.tiles.clicks], ['表示回数', summary.tiles.impressions], ['平均掲載順位', summary.tiles.avgPosition], ['訪問数', summary.tiles.visits], ['登録ユーザー', summary.tiles.usersTotal], ['お気に入り', summary.tiles.favoritesTotal]] as const
  const shown = more ? 50 : 8
  const pct = coverage.sitemapPageCount ? Math.min(100, Math.round(coverage.pagesWithImpressions / coverage.sitemapPageCount * 100)) : 0
  return <main id="main-content" className="page" style={{ maxWidth: 1120, margin: '0 auto', padding: '24px 16px 88px' }}><h1>管理ダッシュボード</h1><p>日次スナップショット（Search Console・Cloudflare Web Analytics・Supabase）</p><p>{([7, 28, 90] as const).map((d) => <button key={d} className="chip" style={{ marginRight: 8 }} onClick={() => setDays(d)} aria-pressed={days === d}>{d}日</button>)}</p><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(145px,1fr))', gap: 10 }}>{tiles.map(([label, value]) => <div key={label} className="card"><small>{label}</small><b style={{ display: 'block', fontSize: 24 }}>{fmt(value)}</b></div>)}</section><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: 12 }}><div className="card"><h2>クリック数 / 日</h2><LineChart dates={summary.series.dates} values={summary.series.clicks} /></div><div className="card"><h2>表示回数 / 日</h2><LineChart dates={summary.series.dates} values={summary.series.impressions} /></div></section><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: 12 }}><div className="card"><h2>人気クエリ</h2><HBarList rows={queries.slice(0, shown).map((r) => ({ label: r.query ?? '', value: r.clicks }))} /></div><div className="card"><h2>インデックス状況</h2><b>{coverage.pagesWithImpressions.toLocaleString()} / {coverage.sitemapPageCount.toLocaleString()} ページ（{pct}%）</b><div style={{ height: 20, background: '#e7e0d2', marginTop: 8 }}><div style={{ height: '100%', width: `${pct}%`, background: '#e8622a' }} /></div><small>検索表示実績のあるページ数。正確な登録数は GSC 画面で確認してください。</small></div></section><section><h2>人気ページ</h2><RankedTable rows={pages.slice(0, shown)} label="page" /></section><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: 12 }}><div className="card"><h2>訪問数 / 日</h2><LineChart dates={summary.series.dates} values={summary.series.visits} /><h3>流入元</h3><HBarList rows={referers.slice(0, shown).map((r) => ({ label: r.referer, value: r.visits }))} /></div><div className="card"><h2>アプリ内指標</h2><LineChart dates={summary.series.dates} values={summary.series.newUsers} unit="人" /><h3>環境内訳</h3>{Object.entries(dims).map(([type, rows]) => <div key={type}><b>{type}</b><HBarList rows={rows.slice(0, 5).map((r) => ({ label: r.value, value: r.visits }))} /></div>)}</div></section>{(queries.length > 8 || pages.length > 8) && <button className="chip" onClick={() => setMore((v) => !v)}>{more ? '閉じる' : 'もっと見る'}</button>}</main>
}
function RankedTable({ rows, label }: { rows: Ranked; label: 'query' | 'page' }) { return <table><thead><tr><th>{label === 'query' ? 'クエリ' : 'ページ'}</th><th>クリック</th><th>表示</th></tr></thead><tbody>{rows.map((r) => <tr key={r[label]}><td>{r[label]}</td><td>{fmt(r.clicks)}</td><td>{fmt(r.impressions)}</td></tr>)}</tbody></table> }
